//go:build ignore

// Command gencss writes style/code.css from chroma's own style definitions.
//
// The highlighter emits classes rather than inline styles, so the colours live in
// one stylesheet that both markdown code blocks and templ-embedded snippets
// share. Generating it keeps those colours honest: they come from the same
// chroma styles the formatter was configured with, rather than being copied by
// hand and slowly drifting.
//
//	go run tools/gencss/main.go > style/code.css
package main

import (
	"fmt"
	"log"
	"os"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

// The light style must match templates.StyleName, which the formatter uses for
// snippets embedded in templ.
const (
	light = "github"
	dark  = "github-dark"
)

func main() {
	out := os.Stdout

	fmt.Fprintf(out, "/* Generated by tools/gencss. Do not edit by hand.\n"+
		"   Regenerate with: go run tools/gencss/main.go > style/code.css\n"+
		"   Light: %s. Dark: %s.\n\n"+
		"   Both schemes are wrapped in mutually exclusive media queries. That is\n"+
		"   load-bearing: the two chroma styles do not cover the same set of token\n"+
		"   classes. github styles .nx and .p (plain identifiers and punctuation —\n"+
		"   most of any Go snippet) as near-black, and github-dark has no rule for\n"+
		"   them. Emitting the light block unconditionally therefore left near-black\n"+
		"   text on a dark background. */\n\n", light, dark)

	// "not all and (prefers-color-scheme: dark)" matches a light preference and
	// also no preference at all, so there is no third state left unstyled.
	if err := emit(out, "@media not all and (prefers-color-scheme: dark)", light); err != nil {
		log.Fatal(err)
	}
	fmt.Fprintln(out)
	if err := emit(out, "@media (prefers-color-scheme: dark)", dark); err != nil {
		log.Fatal(err)
	}
}

// emit writes one style's CSS wrapped in a media query.
func emit(out *os.File, query, style string) error {
	css, err := styleCSS(style)
	if err != nil {
		return err
	}

	fmt.Fprintf(out, "/* %s */\n%s {\n", style, query)
	for line := range strings.SplitSeq(strings.TrimRight(css, "\n"), "\n") {
		if line == "" {
			fmt.Fprintln(out)
			continue
		}
		fmt.Fprintf(out, "\t%s\n", line)
	}
	fmt.Fprint(out, "}\n")
	return nil
}

func styleCSS(name string) (string, error) {
	style := styles.Get(name)
	if style == nil {
		return "", fmt.Errorf("unknown chroma style %q", name)
	}
	var sb strings.Builder
	f := chromahtml.New(chromahtml.WithClasses(true))
	if err := f.WriteCSS(&sb, style); err != nil {
		return "", err
	}
	return sb.String(), nil
}
