// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/LukasDerBaum42/astwerk/site/templates"
	"github.com/LukasDerBaum42/astwerk/ssg"
)

// Examples hosts live demos. The markup here is what the WASM module hydrates:
// astwerk renders it at build time, and scripts/demo.go attaches behaviour to it
// with reactive.Hydrate. Nothing on this page is rendered twice.
func Examples(c ssg.Ctx) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article class=\"prose\"><h1>Examples</h1><p class=\"lede\">Everything below is one Go file compiled to WebAssembly, hydrating markup this site generated at build time. View source — the HTML is all there before any script runs.</p><h2>A counter</h2><p>The smallest useful thing: a signal, a text binding, two handlers. The markup is static; only the number changes.</p><div class=\"demo\" id=\"counter\"><button data-dec aria-label=\"Decrement\">&minus;</button> <output data-count>0</output> <button data-inc aria-label=\"Increment\">+</button><p class=\"demo-note\">Parity: <strong data-parity>even</strong></p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templates.CodeBlock(counterSrc).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<h2>A keyed list</h2><p>Add and remove rows. Entries are keyed, so existing nodes are moved rather than rebuilt — type into a row, then add another and watch the text you typed survive.</p><div class=\"demo\" id=\"todo\"><form data-form><input data-new type=\"text\" placeholder=\"Something to do\" aria-label=\"New item\"> <button type=\"submit\" data-add>Add</button></form><ul data-list class=\"todo-list\"></ul><p class=\"demo-note\"><strong data-remaining>0</strong> remaining</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templates.CodeBlock(listSrc).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h2>Canvas</h2><p>A typed 2D context and an animation loop, with the drawing buffer matched to the device pixel ratio so it stays sharp.</p><div class=\"demo\" id=\"canvas-demo\"><canvas data-canvas width=\"600\" height=\"200\"></canvas><p><button data-toggle>Pause</button> <span class=\"demo-note\">Move the pointer over the canvas.</span></p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templates.CodeBlock(canvasSrc).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<noscript><p class=\"warn\">These demos need WebAssembly. The page content above is static HTML and reads fine without it.</p></noscript></article>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templates.WasmScript(c, "demo").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = templates.Layout(c, nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

const counterSrc = `count := reactive.NewSignal(0)
parity := reactive.Computed(func() string {
	if count.Get()%2 == 0 {
		return "even"
	}
	return "odd"
})

reactive.Hydrate("#counter", func(root wasmwrap.Element) {
	reactive.BindText(root.Find("[data-count]"), func() string {
		return strconv.Itoa(count.Get())
	})
	reactive.BindText(root.Find("[data-parity]"), parity.Get)

	reactive.On(root.Find("[data-inc]"), "click", func(wasmwrap.Event) {
		count.Update(func(v int) int { return v + 1 })
	})
	reactive.On(root.Find("[data-dec]"), "click", func(wasmwrap.Event) {
		count.Update(func(v int) int { return v - 1 })
	})
})`

const listSrc = `type Item struct {
	ID   string
	Text string
}

items := reactive.NewSignal([]Item{})

reactive.BindList(list, items.Get,
	func(it Item) string { return it.ID },
	func(it Item) wasmwrap.Element {
		row := wasmwrap.Create("li")
		field := wasmwrap.Create("input").SetInputValue(it.Text)
		remove := wasmwrap.Create("button").SetText("remove")

		reactive.On(remove, "click", func(wasmwrap.Event) {
			items.Update(func(all []Item) []Item {
				return slices.DeleteFunc(all, func(o Item) bool {
					return o.ID == it.ID
				})
			})
		})
		return row.Append(field, remove)
	})`

const canvasSrc = `canvas := root.Find("[data-canvas]").AsCanvas()
ctx2d := canvas.Context2D()
w, h := canvas.FitToDisplay(ctx2d)

pointer := reactive.NewSignal(0.0)
reactive.On(canvas.Element(), "pointermove", func(e wasmwrap.Event) {
	x, _ := e.PosIn(canvas.Element())
	pointer.Set(float64(x))
})

elapsed := 0.0
cancel := ctx2d.RequestAnimationFrame(func(dt float64) {
	elapsed += dt
	ctx2d.Clear(0, 0, w, h)
	for i := 0.0; i < w; i += 6 {
		wave := math.Sin(i/40+elapsed*2) * 40
		lift := math.Exp(-math.Pow(i-pointer.Peek(), 2) / 4000) * 30
		ctx2d.FillStyle("#4f7cff").FillRect(i, h/2+wave-lift, 3, 3)
	}
})`

var _ = templruntime.GeneratedTemplate
